#!/bin/bash

CP="out/classes;out/testclasses;asm-all-2.2.3.jar;junit-4.8.1.jar"
rm -rf out
mkdir -p out/classes
mkdir -p out/testclasses
mkdir -p out/testweave
javac -cp "$CP" -g -d out/classes `find src/main/java -name "*.java"`
javac -cp "$CP" -g -d out/testclasses `find src/test/java -name "*.java"`
java -cp "$CP" -ea org.fuwjin.milik.tools.Asm -d out/testclasses `find src/test/java -name "*.j"`

java -cp "$CP" -ea org.fuwjin.milik.tools.Weaver -d out/classes -x "ExInvalid" out/classes
java -cp "$CP" -ea junit.textui.TestRunner org.fuwjin.milik.test.AllNotWoven

java -cp "$CP" -ea org.fuwjin.milik.tools.Weaver -d out/testclasses -x "ExInvalid" out/testclasses
java -cp "$CP" -ea junit.textui.TestRunner org.fuwjin.milik.test.AllWoven

jar cf milik.jar -C out/classes .