/*******************************************************************************
 * Copyright (c) 2010 Michael Doberenz.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Michael Doberenz - initial implementation
 *******************************************************************************/
package org.fuwjin.pogo;

import static java.util.Collections.unmodifiableMap;
import static org.fuwjin.pogo.PredefinedGrammar.PogoSerial;
import static org.fuwjin.util.ObjectUtils.eq;
import static org.fuwjin.util.ObjectUtils.hash;

import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;

import org.fuwjin.pogo.parser.Rule;

/**
 * The parser generated by PogoGrammar.
 */
public class Grammar extends Pogo implements Iterable<Parser> {
   private static final String GRAMMAR = "Grammar"; //$NON-NLS-1$
   private final Map<String, Parser> rules = new LinkedHashMap<String, Parser>();
   private static Pogo serial;

   @Override
   public boolean equals(final Object obj) {
      try {
         final Grammar o = (Grammar)obj;
         return eq(getClass(), o.getClass()) && eq(rules, o.rules);
      } catch(final ClassCastException e) {
         return false;
      }
   }

   /**
    * Retrieves a rule from the grammar by name.
    * @param name the name of the rule
    * @return the rule by that name, or null if there is no such rule
    */
   public Pogo get(final String name) {
      final Parser rule = rules.get(name);
      if(rule == null) {
         throw new IllegalArgumentException(name);
      }
      return new Pogo(rule);
   }

   @Override
   public int hashCode() {
      return hash(getClass(), rules);
   }

   public Iterator<Parser> iterator() {
      return rules.values().iterator();
   }

   @Override
   public String toString() {
      if(serial == null) {
         serial = PogoSerial.get(GRAMMAR);
      }
      return serial.serial(this);
   }

   /**
    * Adds a new rule to the grammar.
    * @param rule the new rule
    */
   protected void add(final Rule rule) {
      if(rules.isEmpty()) {
         setRule(rule);
      }
      rules.put(rule.name(), rule);
   }

   /**
    * Resolves the rules in this grammar.
    * @return this grammar
    */
   protected Grammar resolve() {
      for(final Parser rule: rules.values()) {
         rule.resolve(unmodifiableMap(rules), null);
      }
      return this;
   }
}
