package org.fuwjin.postage.category;

import org.fuwjin.postage.Failure;
import org.fuwjin.postage.Function;
import org.fuwjin.postage.FunctionTarget;
import org.fuwjin.postage.function.ConstantFunction;

/**
 * A category which by default returns failure functions. Individual functions
 * may be added to the category.
 */
public class VoidCategory extends AbstractCategory {
   private final FunctionMap map = new FunctionMap();

   /**
    * Creates a new instance. Though the prefix can be any string, it is
    * suggested that to avoid conflicting with normal java classes, that
    * keywords such as void or default be used.
    * @param prefix the prefix for functions generated by this factory
    */
   public VoidCategory(final String prefix) {
      super(prefix);
   }

   /**
    * Adds a function to the category.
    * @param name the name of the function
    * @param function the function
    */
   public void addFunction(final String name, final FunctionTarget function) {
      map.put(name, function);
   }

   @Override
   public Function getTargetFunction(final String name) {
      Function func = map.get(name);
      if(func == null) {
         final FunctionTarget target = new ConstantFunction(new Failure("No such function %s defined for category %s",
               name, this));
         func = map.put(name, target);
      }
      return func;
   }
}
